management:
  server:
    port: 8080
  endpoints:
    prometheus:
      enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
      enabled: true
    web:
      exposure:
        include: "prometheus"

spring:
  application:
    name: PocKotinCleArchitecture